name: AdminWatcher
version: '${project.version}'
main: pl.grokdev.adminwatcher.AdminWatcher
api-version: 1.21
load: STARTUP
author: Grok MC Developer
description: Zaawansowane monitorowanie administracji - gm1, give, podejrzane akcje + Discord

commands:
  adminwatcher:
    description: Główna komenda pluginu
    usage: /<command> reload
    permission: adminwatcher.admin
  adminlogs:
    description: Przeglądanie logów administracji
    usage: /<command> [ilość]
    permission: adminwatcher.admin

permissions:
  adminwatcher.admin:
    default: op
  adminwatcher.bypass:
    default: false